dictCountries = {'Afghanistan': 'Afghanistan', 'Albania': 'Albania',
                 'Algeria': 'Algeria', 'Andorra': 'Andorra', 'Angola': 'Angola',
                 'Antigua and Barbuda': 'Antigua_and_Barbuda',
                 'Argentina': 'Argentina', 'Armenia': 'Armenia',
                 'Australia': 'Australia', 'Austria': 'Austria',
                 'Azerbaijan': 'Azerbaijan',
                 'The Bahamas': 'The_Bahamas', 'Bahrain': 'Bahrain',
                 'Bangladesh': 'Bangladesh', 'Barbados': 'Barbados',
                 'Belarus': 'Belarus', 'Belgium': 'Belgium', 'Belize': 'Belize',
                 'Benin': 'Benin', 'Bhutan': 'Bhutan', 'Bolivia': 'Bolivia',
                 'Bosnia and Herzegovina': 'Bosnia_and_Herzegovina',
                 'Botswana': 'Botswana', 'Brazil': 'Brazil', 'Brunei': 'Brunei',
                 'Bulgaria': 'Bulgaria', 'Burkina Faso': 'Burkina_Faso',
                 'Burundi': 'Burundi',
                 'Cambodia': 'Cambodia', 'Cameroon': 'Cameroon',
                 'Canada': 'Canada',
                 'Central African Republic': 'Central_African_Republic',
                 'Chad': 'Chad', 'Chile': 'Chile', 'China': 'China',
                 'Colombia': 'Colombia', 'Comoros':'Comoros',
                 'Democratic Republic of the Congo': 'Democratic_Republic_of_the_Congo',
                 'Republic of the Congo': 'Republic_of_the_Congo',
                 'Costa Rica': 'Costa_Rica', 'Croatia': 'Croatia',
                 'Cuba': 'Cuba', 'Cyprus': 'Cyprus',
                 'Czech Republic': 'Czech_Republic', 'Denmark': 'Denmark',
                 'Djibouti': 'Djibouti', 'Dominica': 'Dominica',
                 'Dominican Republic': 'Dominican_Republic',
                 'East Timor': 'East_Timor', 'Ecuador': 'Ecuador',
                 'Egypt': 'Egypt', 'El Salvador': 'El_Salvador',
                 'Equatorial Guinea': 'Equatorial_Guinea',
                 'Eritrea': 'Eritrea', 'Estonia': 'Estonia', 'Ethiopia': 'Ethiopia',
                 'Fiji': 'Fiji', 'Finland': 'Finland', 'France': 'France',
                 'Gabon': 'Gabon', 'Gambia': 'The_Gambia', 'Georgia': 'Georgia',
                 'Germany': 'Germany', 'Ghana': 'Ghana', 'Greece': 'Greece',
                 'Grenada': 'Grenada', 'Guatemala': 'Guatemala',
                 'Guinea': 'Guinea', 'Guinea-Bissau': 'Guinea-Bissau',
                 'Guyana': 'Guyana', 'Haiti': 'Haiti',
                 'Honduras': 'Honduras', 'Hungary': 'Hungary',
                 'Iceland': 'Iceland', 'India': 'India',
                 'Indonesia': 'Indonesia', 'Iran': 'Iran', 'Iraq': 'Iraq',
                 'Ireland': 'Ireland', 'Israel': 'Israel', 'Italy': 'Italy',
                 'Ivory Coast': 'Ivory_Coast', 'Jamaica': 'Jamaica',
                 'Japan': 'Japan', 'Jordan': 'Jordan',
                 'Kazakhstan': 'Kazakhstan', 'Kenya': 'Kenya',
                 'Kiribati': 'Kiribati', 'Kuwait': 'Kuwait',
                 'Kyrgyzstan': 'Kyrgyzstan', 'Laos': 'Laos', 'Latvia': 'Latvia',
                 'Lebanon': 'Lebanon', 'Lesotho': 'Lesotho',
                 'Liberia': 'Liberia', 'Libya': 'Libya',
                 'Liechtenstein': 'Liechtenstein', 'Lithuania': 'Lithuania',
                 'Luxembourg': 'Luxembourg', 'Macedonia': 'Repuclic_of_Macedonia',
                 'Madagascar': 'Madagascar', 'Malawi': 'Malawi',
                 'Malaysia': 'Malaysia', 'Maldives': 'Maldives', 'Mali': 'Mali',
                 'Malta': 'Malta', 'Marshall Islands': 'Marshall_Islands',
                 'Mauritania': 'Mauritania', 'Mauritus': 'Mauritus',
                 'Mexico': 'Mexico', 'Micronesia': 'Micronesia',
                 'Moldova': 'Moldova', 'Monaco': 'Monaco',
                 'Mongolia': 'Mongolia', 'Montenegro': 'Montenegro',
                 'Morocco': 'Morocco', 'Mozambique': 'Mozambique',
                 'Myanmar': 'Myanmar', 'Namibia': 'Namibia', 'Nauru': 'Nauru',
                 'Nepal': 'Nepal', 'Kingdom of the Netherlands': 'Kingdom_of_the_Netherlands',
                 'New Zealand': 'New_Zealand', 'Nicaragua': 'Nicaragua',
                 'Niger': 'Niger', 'Nigeria': 'Nigeria', 'North Korea': 'North_Korea',
                 'Norway': 'Norway', 'Oman': 'Oman', 'Pakistan': 'Pakistan',
                 'Palau': 'Palau', 'Palestine': 'State_of_Palestine',
                 'Panama': 'Panama', 'Papua New Guinea': 'Papua_New_Guinea',
                 'Paraguay': 'Paraguay', 'Peru': 'Peru',
                 'Philippines': 'Philippines', 'Poland': 'Poland',
                 'Portugal': 'Portugal', 'Qatar': 'Qatar', 'South Korea': 'South_Korea',
                 'Republic of the Congo': 'Republic_of_the_Congo',
                 'Romania': 'Romania', 'Russia': 'Russia', 'Rwanda': 'Rwanda',
                 'Saint Kitts and Nevis': 'Saint_Kitts_and_Nevis',
                 'Saint Lucia': 'Saint_Lucia',
                 'Saint Vincent and the Grenadines': 'Saint_Vincent_and_the_Grenadines',
                 'Samoa': 'Samoa', 'San Marino': 'San_Marino',
                 'Sao Tome and Principe': 'Sao_Tome_and_Principe',
                 'Saudi Arabia': 'Saudi_Arabia', 'Senegal': 'Senegal',
                 'Serbia': 'Serbia', 'Seychelles': 'Seychelles',
                 'Sierra Leone': 'Sierra_Leone', 'Singapore': 'Singapore',
                 'Slovakia': 'Slovakia', 'Slovenia': 'Slovenia',
                 'Solomon Islands': 'Solomon_Islands', 'Somalia': 'Somalia',
                 'South Africa': 'South_Africa', 'South Korea': 'South_Korea',
                 'South Sudan': 'South_Sudan', 'Spain': 'Spain', 'Sri Lanka': 'Sri_Lanka',
                 'Sudan': 'Sudan', 'Suriname': 'Suriname', 'Swaziland': 'Swaziland',
                 'Sweden': 'Sweden', 'Switzerland': 'Switzerland', 'Syria': 'Syria',
                 'Taiwan': 'Taiwan', 'Tajikistan': 'Tajikistan', 'Tanzania': 'Tanzania',
                 'Thailand': 'Thailand', 'East Timor': 'East_Timor', 'Togo': 'Togo',
                 'Tonga': 'Tonga', 'Transnistria': 'Transnistria',
                 'Trinidad and Tobago': 'Trinidad_and_Tobago',
                 'Tunisia': 'Tunisia', 'Turkey': 'Turkey', 'Turkmenistan': 'Turkmenistan',
                 'Tuvalu': 'Tuvalu', 'Uganda': 'Uganda', 'Ukraine': 'Ukraine',
                 'United Arab Emirates': 'United_Arab_Emirates',
                 'United Kingdom': 'United_Kingdom', 'United States': 'United_States',
                 'Uruguay': 'Uruguay', 'Uzbekistan': 'Uzbekistan',
                 'Vanuatu': 'Vanuatu', 'Vatican City': 'Vatican_City',
                 'Venezuela': 'Venezuela', 'Vietnam': 'Vietnam',
                 'Yemen': 'Yemen',
                 'Zambia': 'Zambia', 'Zimbabwe': 'Zimbabwe'}
print(dictCountries)
